Preprocess Data

In [19]:
import pandas as pd
df = pd.read_csv('final_dataset.csv', low_memory=False)

numeric_columns = df.select_dtypes(include=['float64', 'int64']).columns
print(numeric_columns)

df.head()

Index(['academicYear', 'idOSYM', 'scholarshipRate', 'quota', 'occupiedSlots',
       'tuitionFee', 'profCount', 'assoCount', 'docCount', 'baseRanking',
       'topRanking', 'stdDeviationStudents', 'revenue', 'outOfCityStudentRate',
       'sameRegionStudentRate', 'totalPreference', 'top1PreferenceRatio',
       'top3PreferenceRatio', 'top9PreferenceRatio', 'avgOrderofPreference',
       'avgAdmittedStudentPrefOrder', 'top1AdmittedRatio', 'top3AdmittedRatio',
       'top10AdmittedRatio', 'admittedGovPref', 'admittedPrivPref',
       'admittedTotalPref', 'admittedTotalDepartmentPref',
       'currentStudentCount', 'totalForeignStudents', 'totalStudentNumber',
       'Urap_Rank', 'Urap_Score', 'Time_for_employment', 'employment_rate',
       'avg_monthly_income_group', 'base_salary_by_year', 'inflation_by_year',
       'growth_by_year', 'avgAdmissionRanking', 'baseAdmissionRanking'],
      dtype='object')

,academicYear,universityName,universityType,faculty,departmentName,idOSYM,programType,language,scholarshipRate,quota,...,Urap_Rank,Urap_Score,Time_for_employment,employment_rate,avg_monthly_income_group,base_salary_by_year,inflation_by_year,growth_by_year,avgAdmissionRanking,baseAdmissionRanking
0,2021,ABDULLAH GÜL ÜNİVERSİTESİ,devlet,Mühendislik Fakültesi,Bilgisayar Mühendisliği,106510077,SAY,İngilizce,0.0,70,...,40.0,506.880000,11.2,90.1,2.0,2825,64,11.6,54.466,112.334
1,2021,ABDULLAH GÜL ÜNİVERSİTESİ,devlet,Mühendislik Fakültesi,Bilgisayar Mühendisliği,106510077,SAY,İngilizce,0.0,70,...,40.0,506.880000,11.2,90.1,2.0,2825,64,11.6,54.466,112.334
2,2022,ABDULLAH GÜL ÜNİVERSİTESİ,devlet,Mühendislik Fakültesi,Bilgisayar Mühendisliği,106510077,SAY,İngilizce,0.0,75,...,43.0,716.794001,11.2,90.1,2.0,5500,64,5.4,41.365,114.126
3,2022,ABDULLAH GÜL ÜNİVERSİTESİ,devlet,Mühendislik Fakültesi,Bilgisayar Mühendisliği,106510077,SAY,İngilizce,0.0,75,...,43.0,716.794001,11.2,90.1,2.0,5500,64,5.4,41.365,114.126
4,2023,ABDULLAH GÜL ÜNİVERSİTESİ,devlet,Mühendislik Fakültesi,Bilgisayar Mühendisliği,106510077,SAY,İngilizce,0.0,75,...,50.0,705.460000,10.8,90.8,2.0,11402,36,3.8,44.487,158.876

In [20]:
non_numeric_columns = df.select_dtypes(exclude=['number']).columns
print(non_numeric_columns)

Index(['universityName', 'universityType', 'faculty', 'departmentName',
       'programType', 'language', 'universityLocation', 'universityRegion'],
      dtype='object')

In [21]:
numeric_columns = df.select_dtypes(include=['float64', 'int64']).columns

# Check for non-numeric values and missing values
non_numeric_counts = {}
missing_counts = {}

for col in numeric_columns:
    # Convert to numeric and count non-numeric values
    non_numeric_counts[col] = df[col].apply(pd.to_numeric, errors='coerce').isnull().sum()
    # Count missing values
    missing_counts[col] = df[col].isnull().sum()

# Print non-numeric and missing value counts
print("Non-numeric value counts in numeric columns:")
print(non_numeric_counts)
print("\nMissing value counts in numeric columns:")
print(missing_counts)

# Get summary statistics for numeric columns
summary_statistics = df[numeric_columns].describe()
print("\nSummary statistics for numeric columns:")
print(summary_statistics)

Non-numeric value counts in numeric columns:
{'academicYear': np.int64(0), 'idOSYM': np.int64(0), 'scholarshipRate': np.int64(0), 'quota': np.int64(0), 'occupiedSlots': np.int64(0), 'tuitionFee': np.int64(0), 'profCount': np.int64(0), 'assoCount': np.int64(0), 'docCount': np.int64(0), 'baseRanking': np.int64(0), 'topRanking': np.int64(0), 'stdDeviationStudents': np.int64(0), 'revenue': np.int64(0), 'outOfCityStudentRate': np.int64(0), 'sameRegionStudentRate': np.int64(0), 'totalPreference': np.int64(0), 'top1PreferenceRatio': np.int64(0), 'top3PreferenceRatio': np.int64(0), 'top9PreferenceRatio': np.int64(0), 'avgOrderofPreference': np.int64(0), 'avgAdmittedStudentPrefOrder': np.int64(0), 'top1AdmittedRatio': np.int64(0), 'top3AdmittedRatio': np.int64(0), 'top10AdmittedRatio': np.int64(0), 'admittedGovPref': np.int64(0), 'admittedPrivPref': np.int64(0), 'admittedTotalPref': np.int64(0), 'admittedTotalDepartmentPref': np.int64(0), 'currentStudentCount': np.int64(0), 'totalForeignStudents': np.int64(0), 'totalStudentNumber': np.int64(0), 'Urap_Rank': np.int64(0), 'Urap_Score': np.int64(0), 'Time_for_employment': np.int64(0), 'employment_rate': np.int64(0), 'avg_monthly_income_group': np.int64(0), 'base_salary_by_year': np.int64(0), 'inflation_by_year': np.int64(0), 'growth_by_year': np.int64(0), 'avgAdmissionRanking': np.int64(0), 'baseAdmissionRanking': np.int64(0)}

Missing value counts in numeric columns:
{'academicYear': np.int64(0), 'idOSYM': np.int64(0), 'scholarshipRate': np.int64(0), 'quota': np.int64(0), 'occupiedSlots': np.int64(0), 'tuitionFee': np.int64(0), 'profCount': np.int64(0), 'assoCount': np.int64(0), 'docCount': np.int64(0), 'baseRanking': np.int64(0), 'topRanking': np.int64(0), 'stdDeviationStudents': np.int64(0), 'revenue': np.int64(0), 'outOfCityStudentRate': np.int64(0), 'sameRegionStudentRate': np.int64(0), 'totalPreference': np.int64(0), 'top1PreferenceRatio': np.int64(0), 'top3PreferenceRatio': np.int64(0), 'top9PreferenceRatio': np.int64(0), 'avgOrderofPreference': np.int64(0), 'avgAdmittedStudentPrefOrder': np.int64(0), 'top1AdmittedRatio': np.int64(0), 'top3AdmittedRatio': np.int64(0), 'top10AdmittedRatio': np.int64(0), 'admittedGovPref': np.int64(0), 'admittedPrivPref': np.int64(0), 'admittedTotalPref': np.int64(0), 'admittedTotalDepartmentPref': np.int64(0), 'currentStudentCount': np.int64(0), 'totalForeignStudents': np.int64(0), 'totalStudentNumber': np.int64(0), 'Urap_Rank': np.int64(0), 'Urap_Score': np.int64(0), 'Time_for_employment': np.int64(0), 'employment_rate': np.int64(0), 'avg_monthly_income_group': np.int64(0), 'base_salary_by_year': np.int64(0), 'inflation_by_year': np.int64(0), 'growth_by_year': np.int64(0), 'avgAdmissionRanking': np.int64(0), 'baseAdmissionRanking': np.int64(0)}

Summary statistics for numeric columns:
       academicYear        idOSYM  scholarshipRate         quota  \
count  54496.000000  5.449600e+04     54496.000000  54496.000000
mean    2022.041232  1.444946e+08        26.823070     46.557068
std        0.814836  4.816880e+07        39.847604     83.549279
min     2021.000000  1.001100e+08         0.000000      1.000000
25%     2021.000000  1.048103e+08         0.000000     15.000000
50%     2022.000000  1.094107e+08         0.000000     40.000000
75%     2023.000000  2.027109e+08        50.000000     60.000000
max     2023.000000  2.104026e+08       100.000000   4800.000000

       occupiedSlots     tuitionFee     profCount     assoCount      docCount  \
count   54496.000000   54496.000000  54496.000000  54496.000000  54496.000000
mean       43.527708   19718.074698      3.758247      2.060907      3.827902
std        81.248811   53397.585004     14.923165      5.584895      7.354682
min         0.000000       0.000000      0.000000      0.000000      0.000000
25%        10.000000       0.000000      0.000000      0.000000      0.000000
50%        34.000000       0.000000      1.000000      1.000000      2.000000
75%        62.000000       0.000000      3.000000      2.000000      4.000000
max      4920.000000  709506.000000    321.000000    106.000000    110.000000

        baseRanking  ...     Urap_Rank    Urap_Score  Time_for_employment  \
count  54496.000000  ...  54496.000000  54496.000000         54496.000000
mean     266.225876  ...     74.374578    546.546192             9.620855
std      230.290905  ...     53.474940    239.569516             7.077990
min        0.000000  ...      0.000000      0.000000             0.000000
25%       71.401000  ...     27.000000    405.749722             0.000000
50%      221.182500  ...     65.000000    545.260000            11.200000
75%      385.424052  ...    120.000000    704.300000            14.900000
max      999.818000  ...    188.000000   1126.410000            24.500000

       employment_rate  avg_monthly_income_group  base_salary_by_year  \
count     54496.000000              54496.000000         54496.000000
mean         55.325628                 -0.031764          6750.843585
std          36.521383                  1.156209          3602.944228
min           0.000000                 -2.000000          2825.000000
25%           0.000000                 -1.000000          2825.000000
50%          72.100000                  0.000000          5500.000000
75%          82.700000                  0.000000         11402.000000
max          96.200000                  2.000000         11402.000000

       inflation_by_year  growth_by_year  avgAdmissionRanking  \
count       54496.000000    54496.000000         54496.000000
mean           54.103714        6.770178           403.543709
std            13.385172        3.320969           244.503864
min            36.000000        3.800000             1.012000
25%            36.000000        3.800000           208.722000
50%            64.000000        5.400000           392.961000
75%            64.000000       11.600000           551.776000
max            64.000000       11.600000           999.966000

       baseAdmissionRanking
count          54496.000000
mean             514.658449
std              234.314286
min                0.000000
25%              359.508250
50%              556.760167
75%              653.987750
max              999.951000

[8 rows x 41 columns]

Encoding Non-numeric Values

In [22]:
print('Non-numeric columns:', non_numeric_columns)

Non-numeric columns: Index(['universityName', 'universityType', 'faculty', 'departmentName',
       'programType', 'language', 'universityLocation', 'universityRegion'],
      dtype='object')

In [23]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

# One-hot encoding
one_hot_columns = ['universityType', 'programType', 'language']
df = pd.get_dummies(df, columns=one_hot_columns)

# Label encoding
label_columns = ['universityLocation', 'universityRegion']
label_encoder = LabelEncoder()
for col in label_columns:
    df[col] = label_encoder.fit_transform(df[col])
    
# Target encoding
df['universityName_encoded'] = df.groupby('universityName')['baseRanking'].transform('mean')
df['departmentName_encoded'] = df.groupby('departmentName')['baseRanking'].transform('mean')
df['facultyName_encoded'] = df.groupby('faculty')['baseRanking'].transform('mean')

# Drop original columns
df = df.drop(['universityName', 'departmentName', 'faculty'], axis=1)
non_numeric_columns = df.select_dtypes(exclude=['number']).columns

print(non_numeric_columns)

Index(['universityType_devlet', 'universityType_vakıf', 'programType_DİL',
       'programType_EA', 'programType_SAY', 'programType_SÖZ',
       'language_Almanca', 'language_Arapça', 'language_Bulgarca',
       'language_English', 'language_Ermenice', 'language_Fransızca',
       'language_Korece', 'language_Lehçe', 'language_Rusça',
       'language_Turkish', 'language_Türkçe', 'language_Çince',
       'language_İngilizce', 'language_İspanyolca', 'language_İtalyanca'],
      dtype='object')

In [26]:
for col in non_numeric_columns:
    df[col] = df[col].astype(int)
non_numeric_columns = df.select_dtypes(exclude=['number']).columns
print(non_numeric_columns)
df.head()
df.to_csv('final_dataset_encoded.csv', index=False)

Index([], dtype='object')