Preprocess Data

In [1]:
import pandas as pd
df = pd.read_csv('final_dataset.csv', low_memory=False)

numeric_columns = df.select_dtypes(include=['float64', 'int64']).columns
print(numeric_columns)

df.head()

Index(['academicYear', 'idOSYM', 'scholarshipRate', 'quota', 'occupiedSlots',
       'tuitionFee', 'profCount', 'assoCount', 'docCount', 'baseRanking',
       'topRanking', 'stdDeviationStudents', 'revenue', 'outOfCityStudentRate',
       'sameRegionStudentRate', 'totalPreference', 'top1PreferenceRatio',
       'top3PreferenceRatio', 'top9PreferenceRatio', 'avgOrderofPreference',
       'avgAdmittedStudentPrefOrder', 'top1AdmittedRatio', 'top3AdmittedRatio',
       'top10AdmittedRatio', 'admittedGovPref', 'admittedPrivPref',
       'admittedTotalPref', 'admittedTotalDepartmentPref',
       'currentStudentCount', 'totalForeignStudents', 'totalStudentNumber',
       'Urap_Rank', 'Urap_Score', 'avg_monthly_income_group',
       'Time_for_employment', 'employment_rate', 'base_salary_by_year',
       'inflation_by_year', 'growth_by_year', 'avgAdmissionRanking',
       'baseAdmissionRanking'],
      dtype='object')

,academicYear,universityName,universityType,faculty,departmentName,idOSYM,programType,language,scholarshipRate,quota,...,Urap_Rank,Urap_Score,avg_monthly_income_group,Time_for_employment,employment_rate,base_salary_by_year,inflation_by_year,growth_by_year,avgAdmissionRanking,baseAdmissionRanking
0,2021,ABDULLAH GÜL ÜNİVERSİTESİ,devlet,Mühendislik Fakültesi,Bilgisayar Mühendisliği,106510077,SAY,İngilizce,0.0,70,...,40.0,506.880000,2.0,11.2,90.1,2825,64,11.6,54.466,112.334
1,2022,ABDULLAH GÜL ÜNİVERSİTESİ,devlet,Mühendislik Fakültesi,Bilgisayar Mühendisliği,106510077,SAY,İngilizce,0.0,75,...,43.0,716.794001,2.0,11.2,90.1,5500,64,5.4,41.365,114.126
2,2023,ABDULLAH GÜL ÜNİVERSİTESİ,devlet,Mühendislik Fakültesi,Bilgisayar Mühendisliği,106510077,SAY,İngilizce,0.0,75,...,50.0,705.460000,2.0,10.8,90.8,11402,36,3.8,44.487,158.876
3,2021,ABDULLAH GÜL ÜNİVERSİTESİ,devlet,Yaşam ve Doğa Bilimleri Fakültesi,Biyomühendislik,106510087,SAY,İngilizce,0.0,60,...,40.0,506.880000,0.0,16.6,71.2,2825,64,11.6,275.467,949.204
4,2022,ABDULLAH GÜL ÜNİVERSİTESİ,devlet,Yaşam ve Doğa Bilimleri Fakültesi,Biyomühendislik,106510087,SAY,İngilizce,0.0,65,...,43.0,716.794001,0.0,16.6,71.2,5500,64,5.4,252.682,622.839

In [2]:
non_numeric_columns = df.select_dtypes(exclude=['number']).columns
print(non_numeric_columns)

Index(['universityName', 'universityType', 'faculty', 'departmentName',
       'programType', 'language', 'universityLocation', 'universityRegion'],
      dtype='object')

In [3]:
numeric_columns = df.select_dtypes(include=['float64', 'int64']).columns

non_numeric_counts = {}
missing_counts = {}

for col in numeric_columns:
    non_numeric_counts[col] = df[col].apply(pd.to_numeric, errors='coerce').isnull().sum()
    missing_counts[col] = df[col].isnull().sum()

# Print non-numeric and missing value counts
print("Non-numeric value counts in numeric columns:")
print(non_numeric_counts)
print("\nMissing value counts in numeric columns:")
print(missing_counts)

# Get summary statistics for numeric columns
summary_statistics = df[numeric_columns].describe()
print("\nSummary statistics for numeric columns:")
print(summary_statistics)

Non-numeric value counts in numeric columns:
{'academicYear': np.int64(0), 'idOSYM': np.int64(0), 'scholarshipRate': np.int64(0), 'quota': np.int64(0), 'occupiedSlots': np.int64(0), 'tuitionFee': np.int64(0), 'profCount': np.int64(0), 'assoCount': np.int64(0), 'docCount': np.int64(0), 'baseRanking': np.int64(0), 'topRanking': np.int64(0), 'stdDeviationStudents': np.int64(0), 'revenue': np.int64(0), 'outOfCityStudentRate': np.int64(0), 'sameRegionStudentRate': np.int64(0), 'totalPreference': np.int64(0), 'top1PreferenceRatio': np.int64(0), 'top3PreferenceRatio': np.int64(0), 'top9PreferenceRatio': np.int64(0), 'avgOrderofPreference': np.int64(0), 'avgAdmittedStudentPrefOrder': np.int64(0), 'top1AdmittedRatio': np.int64(0), 'top3AdmittedRatio': np.int64(0), 'top10AdmittedRatio': np.int64(0), 'admittedGovPref': np.int64(0), 'admittedPrivPref': np.int64(0), 'admittedTotalPref': np.int64(0), 'admittedTotalDepartmentPref': np.int64(0), 'currentStudentCount': np.int64(0), 'totalForeignStudents': np.int64(0), 'totalStudentNumber': np.int64(0), 'Urap_Rank': np.int64(0), 'Urap_Score': np.int64(0), 'avg_monthly_income_group': np.int64(0), 'Time_for_employment': np.int64(0), 'employment_rate': np.int64(0), 'base_salary_by_year': np.int64(0), 'inflation_by_year': np.int64(0), 'growth_by_year': np.int64(0), 'avgAdmissionRanking': np.int64(0), 'baseAdmissionRanking': np.int64(0)}

Missing value counts in numeric columns:
{'academicYear': np.int64(0), 'idOSYM': np.int64(0), 'scholarshipRate': np.int64(0), 'quota': np.int64(0), 'occupiedSlots': np.int64(0), 'tuitionFee': np.int64(0), 'profCount': np.int64(0), 'assoCount': np.int64(0), 'docCount': np.int64(0), 'baseRanking': np.int64(0), 'topRanking': np.int64(0), 'stdDeviationStudents': np.int64(0), 'revenue': np.int64(0), 'outOfCityStudentRate': np.int64(0), 'sameRegionStudentRate': np.int64(0), 'totalPreference': np.int64(0), 'top1PreferenceRatio': np.int64(0), 'top3PreferenceRatio': np.int64(0), 'top9PreferenceRatio': np.int64(0), 'avgOrderofPreference': np.int64(0), 'avgAdmittedStudentPrefOrder': np.int64(0), 'top1AdmittedRatio': np.int64(0), 'top3AdmittedRatio': np.int64(0), 'top10AdmittedRatio': np.int64(0), 'admittedGovPref': np.int64(0), 'admittedPrivPref': np.int64(0), 'admittedTotalPref': np.int64(0), 'admittedTotalDepartmentPref': np.int64(0), 'currentStudentCount': np.int64(0), 'totalForeignStudents': np.int64(0), 'totalStudentNumber': np.int64(0), 'Urap_Rank': np.int64(0), 'Urap_Score': np.int64(0), 'avg_monthly_income_group': np.int64(0), 'Time_for_employment': np.int64(0), 'employment_rate': np.int64(0), 'base_salary_by_year': np.int64(0), 'inflation_by_year': np.int64(0), 'growth_by_year': np.int64(0), 'avgAdmissionRanking': np.int64(0), 'baseAdmissionRanking': np.int64(0)}

Summary statistics for numeric columns:
       academicYear        idOSYM  scholarshipRate         quota  \
count  27687.000000  2.768700e+04     27687.000000  27687.000000
mean    2022.040633  1.453905e+08        27.402752     46.149456
std        0.815034  4.838258e+07        40.069664     82.988837
min     2021.000000  1.001100e+08         0.000000      1.000000
25%     2021.000000  1.048108e+08         0.000000     14.000000
50%     2022.000000  1.096102e+08         0.000000     40.000000
75%     2023.000000  2.027905e+08        50.000000     60.000000
max     2023.000000  2.104026e+08       100.000000   4800.000000

       occupiedSlots     tuitionFee     profCount     assoCount      docCount  \
count   27687.000000   27687.000000  27687.000000  27687.000000  27687.000000
mean       43.105609   19394.398032      3.706343      2.032209      3.795034
std        80.709132   51961.789253     14.810692      5.545595      7.309314
min         0.000000       0.000000      0.000000      0.000000      0.000000
25%         9.000000       0.000000      0.000000      0.000000      0.000000
50%        32.000000       0.000000      1.000000      1.000000      2.000000
75%        62.000000       0.000000      3.000000      2.000000      4.000000
max      4920.000000  709506.000000    321.000000    106.000000    110.000000

        baseRanking  ...     Urap_Rank    Urap_Score  \
count  27687.000000  ...  27687.000000  27687.000000
mean     266.488697  ...     74.806263    540.396217
std      230.135596  ...     54.104859    243.190960
min        0.000000  ...      0.000000      0.000000
25%       71.914500  ...     27.000000    399.740000
50%      221.466000  ...     65.000000    540.220000
75%      385.424052  ...    122.000000    703.880000
max      999.818000  ...    188.000000   1126.410000

       avg_monthly_income_group  Time_for_employment  employment_rate  \
count              27687.000000         27687.000000     27687.000000
mean                  -0.031495             9.530928        54.791534
std                    1.149934             7.107253        36.737756
min                   -2.000000             0.000000         0.000000
25%                   -1.000000             0.000000         0.000000
50%                    0.000000            11.200000        71.700000
75%                    0.000000            14.900000        82.500000
max                    2.000000            24.500000        96.200000

       base_salary_by_year  inflation_by_year  growth_by_year  \
count         27687.000000       27687.000000    27687.000000
mean           6748.696572          54.108426        6.773121
std            3603.335712          13.383845        3.322214
min            2825.000000          36.000000        3.800000
25%            2825.000000          36.000000        3.800000
50%            5500.000000          64.000000        5.400000
75%           11402.000000          64.000000       11.600000
max           11402.000000          64.000000       11.600000

       avgAdmissionRanking  baseAdmissionRanking
count         27687.000000          27687.000000
mean            404.257833            515.093243
std             244.222098            233.922132
min               1.012000              0.000000
25%             210.453500            361.855000
50%             393.411000            556.760167
75%             552.033500            654.530988
max             999.966000            999.951000

[8 rows x 41 columns]

Encoding Non-numeric Values

In [4]:
print('Non-numeric columns:', non_numeric_columns)

Non-numeric columns: Index(['universityName', 'universityType', 'faculty', 'departmentName',
       'programType', 'language', 'universityLocation', 'universityRegion'],
      dtype='object')

In [5]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

# One-hot encoding
one_hot_columns = ['universityType', 'programType', 'language']
df = pd.get_dummies(df, columns=one_hot_columns)

# Label encoding
label_columns = ['universityLocation', 'universityRegion']
label_encoder = LabelEncoder()
for col in label_columns:
    df[col] = label_encoder.fit_transform(df[col])
    
# Target encoding
df['universityName_encoded'] = df.groupby('universityName')['baseRanking'].transform('mean')
df['departmentName_encoded'] = df.groupby('departmentName')['baseRanking'].transform('mean')
df['facultyName_encoded'] = df.groupby('faculty')['baseRanking'].transform('mean')

# Drop original columns
df = df.drop(['universityName', 'departmentName', 'faculty'], axis=1)
non_numeric_columns = df.select_dtypes(exclude=['number']).columns

print(non_numeric_columns)

Index(['universityType_devlet', 'universityType_vakıf', 'programType_DİL',
       'programType_EA', 'programType_SAY', 'programType_SÖZ',
       'language_Almanca', 'language_Arapça', 'language_Bulgarca',
       'language_English', 'language_Ermenice', 'language_Fransızca',
       'language_Korece', 'language_Lehçe', 'language_Rusça',
       'language_Turkish', 'language_Türkçe', 'language_Çince',
       'language_İngilizce', 'language_İspanyolca', 'language_İtalyanca'],
      dtype='object')

In [6]:
for col in non_numeric_columns:
    df[col] = df[col].astype(int)
non_numeric_columns = df.select_dtypes(exclude=['number']).columns
print(non_numeric_columns)
df.head()
df.to_csv('final_dataset_encoded.csv', index=False)

Index([], dtype='object')